#!/usr/bin/env bash
#This script allows for file transfer

if [ $# -lt 4 ]; then
	echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
else
	echo "works"
	# PATH = $1
	# IP = $2
	# USERNAME = $3
	# PATH_TO_SSH_KEY = $4
	scp -i "$4" -o StrictHostKeyChecking=no "$1" "$3"@"$2":~/
fi
	
