#!/usr/bin/bash
#installation and configuration of nginx on a new version of ubuntu

# Installation
sudo apt-get update -y
sudo apt-get install nginx -y

#Configuration
sudo service nginx start
echo "Holberton School" > /var/www/html/index.html

