#!/usr/bin/env bash
# advanced task 100
echo $BASHPID > /var/run/holbertonscript.pid
while true; do
	trap 'echo I hate the kill command; rm /var/run/holbertonscript.pid; exit' SIGTERM
	trap 'echo Y U no love me?!' SIGINT
	trap 'rm /var/run/holbertonscript.pid; exit' SIGQUIT
	echo "To infinity and beyond"
	sleep 2
done
