#!/usr/bin/env bash
# This script is fizzbuzz, for every factor of 3 echo Fizz, 5 echo buzz, and both FizzBuzz
i=1
while [ $i -le 100 ];do
	if ! ((i%15))
	then
		echo "FizzBuzz"
	elif [[ $((i%3)) -eq 0 ]]
	then
		echo "Fizz"
	elif [[ $((i%5)) -eq 0 ]]
	then
		echo "Buzz"
	else
		echo "$i"
	fi
	((i+=1))
done
