#!/usr/bin/env bash
# This script is displaying "Holberton School" 10 times and Hi at the ninth time
i=1
while [ $i -lt 11 ];do
	if [ $i -eq 9 ]
	then
		echo "Hi"
	else
		echo "Holberton School"
	fi
	((i++))
done
