#!/usr/bin/env bash
# This script is displaying "Holberton School" 10 times at the 4th iteration it displays "bad luck" at the 8th iteration it displays "good luck"
i=1
while [ $i -le 10 ];do
	if [ $i -eq 4 ]
	then
		echo "bad luck"
	elif [ $i -eq 8 ]
	then
		echo "good luck"
	else
		echo "Holberton School"
	fi
	((i+=1))
done
