#!/usr/bin/env bash
#this script configures host files - using regex sucks
cp /etc/hosts ~/hosts.new
sed -i 's/^127.*$/127.0.0.2 localhost\n8.8.8.8 facebook.com/' ~/hosts.new

# sed -i 's/^127.*$/127.0.0.2 localhost\n8.8.8.8 facebook.com/' ~/hosts.new

# sed -i 's/^127.*$/127.0.0.2 localhost/' /etc/hosts
# 8.8.8.8 facebook.com/ ~/hosts.new
cp -f ~/hosts.new /etc/hosts
