#!/usr/bin/env bash
# this program sets up a server and sets a nginx as user for our server
sudo chown -R nginx:nginx /etc/nginx/nginx.conf
sudo chmod u+rw /etc/nginx/nginx.conf
pkill apache2
sed -i 's/80/8080/' /etc/nginx/sites-available/default
sudo -u nginx service nginx start
